  SELECT VALUENAME,
         ROUND (SUM (VALUE) / EXTRACT (DAY FROM :DBEGIN - 1)) AS VALUE
    FROM RPT_PREV_DATA_33B
   WHERE TRUNC (DATEREPORT, 'DD') BETWEEN TRUNC (:DBEGIN, 'MM')
                                      AND TRUNC (:DBEGIN - 1, 'DD')
GROUP BY VALUENAME